###################################################################

# Created by write_sdc on Mon Nov 13 15:33:33 2023

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 0 [get_ports {DOUT3k[13]}]
set_load -pin_load 0 [get_ports {DOUT3k[12]}]
set_load -pin_load 0 [get_ports {DOUT3k[11]}]
set_load -pin_load 0 [get_ports {DOUT3k[10]}]
set_load -pin_load 0 [get_ports {DOUT3k[9]}]
set_load -pin_load 0 [get_ports {DOUT3k[8]}]
set_load -pin_load 0 [get_ports {DOUT3k[7]}]
set_load -pin_load 0 [get_ports {DOUT3k[6]}]
set_load -pin_load 0 [get_ports {DOUT3k[5]}]
set_load -pin_load 0 [get_ports {DOUT3k[4]}]
set_load -pin_load 0 [get_ports {DOUT3k[3]}]
set_load -pin_load 0 [get_ports {DOUT3k[2]}]
set_load -pin_load 0 [get_ports {DOUT3k[1]}]
set_load -pin_load 0 [get_ports {DOUT3k[0]}]
set_load -pin_load 0 [get_ports {DOUT3k1[13]}]
set_load -pin_load 0 [get_ports {DOUT3k1[12]}]
set_load -pin_load 0 [get_ports {DOUT3k1[11]}]
set_load -pin_load 0 [get_ports {DOUT3k1[10]}]
set_load -pin_load 0 [get_ports {DOUT3k1[9]}]
set_load -pin_load 0 [get_ports {DOUT3k1[8]}]
set_load -pin_load 0 [get_ports {DOUT3k1[7]}]
set_load -pin_load 0 [get_ports {DOUT3k1[6]}]
set_load -pin_load 0 [get_ports {DOUT3k1[5]}]
set_load -pin_load 0 [get_ports {DOUT3k1[4]}]
set_load -pin_load 0 [get_ports {DOUT3k1[3]}]
set_load -pin_load 0 [get_ports {DOUT3k1[2]}]
set_load -pin_load 0 [get_ports {DOUT3k1[1]}]
set_load -pin_load 0 [get_ports {DOUT3k1[0]}]
set_load -pin_load 0 [get_ports {DOUT3k2[13]}]
set_load -pin_load 0 [get_ports {DOUT3k2[12]}]
set_load -pin_load 0 [get_ports {DOUT3k2[11]}]
set_load -pin_load 0 [get_ports {DOUT3k2[10]}]
set_load -pin_load 0 [get_ports {DOUT3k2[9]}]
set_load -pin_load 0 [get_ports {DOUT3k2[8]}]
set_load -pin_load 0 [get_ports {DOUT3k2[7]}]
set_load -pin_load 0 [get_ports {DOUT3k2[6]}]
set_load -pin_load 0 [get_ports {DOUT3k2[5]}]
set_load -pin_load 0 [get_ports {DOUT3k2[4]}]
set_load -pin_load 0 [get_ports {DOUT3k2[3]}]
set_load -pin_load 0 [get_ports {DOUT3k2[2]}]
set_load -pin_load 0 [get_ports {DOUT3k2[1]}]
set_load -pin_load 0 [get_ports {DOUT3k2[0]}]
set_load -pin_load 0 [get_ports VOUT]
create_clock [get_ports CLK]  -period 3.3  -waveform {0 1.65}
set_clock_uncertainty 0.07  [get_clocks CLK]
set_input_delay -clock CLK  -max 0.5  [get_ports RST_n]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k1[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {DIN3k2[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports VIN]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B0[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B1[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B2[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B3[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B4[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B5[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B6[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B7[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B8[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B9[0]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[13]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[12]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[11]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[10]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[9]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[8]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[7]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[6]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[5]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[4]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[3]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[2]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[1]}]
set_input_delay -clock CLK  -max 0.5  [get_ports {B10[0]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[13]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[12]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[11]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[10]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[9]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[8]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[7]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[6]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[5]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[4]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[3]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[2]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[1]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k[0]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[13]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[12]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[11]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[10]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[9]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[8]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[7]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[6]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[5]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[4]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[3]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[2]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[1]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k1[0]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[13]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[12]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[11]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[10]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[9]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[8]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[7]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[6]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[5]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[4]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[3]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[2]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[1]}]
set_output_delay -clock CLK  -max 0.5  [get_ports {DOUT3k2[0]}]
set_output_delay -clock CLK  -max 0.5  [get_ports VOUT]
